SELECT
    C.INCOME_SEGMENT,
    COUNT(F.POLICY_ID)  AS total_policies,
    SUM(F.PREMIUM_AMOUNT) AS total_premium
FROM {{ ref('FACT_POLICY') }} F
JOIN {{ ref('DIM_CUSTOMER') }} C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.INCOME_SEGMENT