SELECT
    ROUND(COUNT(DISTINCT P.POLICY_ID) / NULLIF(COUNT(DISTINCT L.LEAD_ID),0),2) AS conversion_rate
FROM {{ ref('FACT_LEAD') }} L
LEFT JOIN {{ ref('FACT_POLICY') }} P
    ON L.CUSTOMER_ID = P.CUSTOMER_ID